@php($editingStaff = $staff ?? null)
<div class="mt-7 border-t border-slate-200 pt-6">
    <h3 class="text-base font-bold text-slate-800">Employment &amp; Personal Details <span class="text-xs font-normal text-slate-400">(Optional)</span></h3>
    <div class="mt-4 grid grid-cols-1 md:grid-cols-2 gap-5">
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Date of Joining</label><input type="date" name="date_of_joining" value="{{ old('date_of_joining', $editingStaff?->date_of_joining?->format('Y-m-d')) }}" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Designation</label><input type="text" name="designation" value="{{ old('designation', $editingStaff?->designation) }}" placeholder="e.g. Cashier" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Monthly Salary</label><input type="number" name="salary" value="{{ old('salary', $editingStaff?->salary) }}" min="0" step="0.01" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Date of Birth</label><input type="date" name="date_of_birth" value="{{ old('date_of_birth', $editingStaff?->date_of_birth?->format('Y-m-d')) }}" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Gender</label><select name="gender" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"><option value="">Select gender</option>@foreach (['male' => 'Male', 'female' => 'Female', 'other' => 'Other'] as $value => $label)<option value="{{ $value }}" {{ old('gender', $editingStaff?->gender) === $value ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Emergency Contact Name</label><input type="text" name="emergency_contact_name" value="{{ old('emergency_contact_name', $editingStaff?->emergency_contact_name) }}" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Emergency Contact Mobile</label><input type="text" name="emergency_contact_mobile" value="{{ old('emergency_contact_mobile', $editingStaff?->emergency_contact_mobile) }}" maxlength="10" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Bank Name</label><input type="text" name="bank_name" value="{{ old('bank_name', $editingStaff?->bank_name) }}" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Bank Account Number</label><input type="text" name="bank_account_number" value="{{ old('bank_account_number', $editingStaff?->bank_account_number) }}" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">IFSC Code</label><input type="text" name="bank_ifsc_code" value="{{ old('bank_ifsc_code', $editingStaff?->bank_ifsc_code) }}" class="w-full h-12 px-4 rounded-xl border border-slate-200 bg-slate-50 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700 mb-2">Documents</label><input type="file" name="documents[]" multiple accept=".jpg,.jpeg,.png,.pdf,.doc,.docx" class="w-full rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm"><p class="mt-1 text-xs text-slate-400">Optional. Up to 10 files, 10 MB each.</p>@if ($editingStaff && !empty($editingStaff->documents))<div class="mt-2">@foreach ($editingStaff->documents as $document)<a href="{{ asset($document) }}" target="_blank" class="mr-2 text-xs text-[#128C7E] underline">Document {{ $loop->iteration }}</a>@endforeach</div>@endif</div>
        <div class="md:col-span-2"><label class="block text-sm font-semibold text-slate-700 mb-2">Address</label><textarea name="address" rows="3" class="w-full rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm">{{ old('address', $editingStaff?->address) }}</textarea></div>
    </div>
</div>
