@extends('pos.layout.app')

@section('content')
    <div class="flex-1 overflow-y-auto bg-slate-50 p-4 md:p-6"><div class="mx-auto max-w-6xl">
        <div class="mb-6 flex items-center justify-between"><div><a href="{{ route('pos.party-bookings') }}" class="text-xs font-bold text-violet-600 hover:text-violet-800"><i class="fas fa-arrow-left mr-1"></i> Party Bookings</a><h1 class="mt-2 text-2xl font-bold text-slate-800">Booking PR-{{ str_pad((string) $booking->id, 5, '0', STR_PAD_LEFT) }}</h1></div><span class="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">{{ ucfirst($booking->status) }}</span></div>
        <div class="grid gap-5 lg:grid-cols-3"><section class="rounded-2xl border border-violet-100 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-violet-600">Party details</p><h2 class="mt-2 text-xl font-bold text-slate-800">{{ $booking->partyMaster->name ?? 'Party' }}</h2><dl class="mt-5 space-y-3 text-sm"><div><dt class="text-xs text-slate-400">Event date & time</dt><dd class="mt-1 font-semibold">{{ $booking->event_date->format('d M Y') }}{{ $booking->event_time ? ' · ' . \Carbon\Carbon::parse($booking->event_time)->format('h:i A') : '' }}</dd></div><div><dt class="text-xs text-slate-400">Guests</dt><dd class="mt-1 font-semibold">{{ $booking->guest_count }}</dd></div><div><dt class="text-xs text-slate-400">Venue / locality</dt><dd class="mt-1 font-semibold">{{ $booking->venue ?: '-' }}</dd></div><div><dt class="text-xs text-slate-400">Special requirements</dt><dd class="mt-1 leading-6 text-slate-600">{{ $booking->requirements ?: '-' }}</dd></div></dl></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-500">Customer details</p><h2 class="mt-2 text-xl font-bold text-slate-800">{{ $booking->customer_name }}</h2><dl class="mt-5 space-y-3 text-sm"><div><dt class="text-xs text-slate-400">Mobile</dt><dd class="mt-1 font-semibold">{{ $booking->mobile }}</dd></div><div><dt class="text-xs text-slate-400">Email</dt><dd class="mt-1 break-all font-semibold">{{ $booking->email ?: '-' }}</dd></div><div><dt class="text-xs text-slate-400">Store</dt><dd class="mt-1 font-semibold">{{ $booking->store->name ?? '-' }}</dd></div><div><dt class="text-xs text-slate-400">Registered on</dt><dd class="mt-1 font-semibold">{{ $booking->created_at->format('d M Y, h:i A') }}</dd></div></dl></section>
            <section class="rounded-2xl border border-orange-100 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-orange-600">Food order summary</p><p class="mt-2 text-sm text-slate-500">{{ $booking->posOrders->count() }} linked order(s)</p><div class="mt-5 space-y-3">@forelse($booking->posOrders as $order)<div class="rounded-xl bg-orange-50 p-3"><div class="flex items-center justify-between gap-2"><p class="font-bold text-orange-700">{{ $order->order_number }}</p><span class="text-xs font-bold {{ $order->payment_status === 'completed' ? 'text-emerald-600' : 'text-amber-600' }}">{{ ucfirst($order->payment_status ?? 'pending') }}</span></div><p class="mt-1 text-sm font-semibold text-slate-700">₹{{ number_format($order->grand_total, 2) }}</p><a href="{{ route('pos.customer-orders.view', $order) }}" class="mt-3 inline-flex text-xs font-bold text-orange-700 hover:text-orange-900">View ordered items <i class="fas fa-arrow-right ml-1"></i></a></div>@empty<div class="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Customer has not placed a food order yet.</div>@endforelse</div></section>
        </div>
        <section class="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold text-slate-800">Ordered food items</h2></div><div class="divide-y divide-slate-100">@forelse($booking->posOrders as $order)<div class="p-5"><div class="mb-3 flex flex-wrap items-center justify-between gap-2"><p class="font-bold text-slate-800">{{ $order->order_number }}</p><p class="text-sm font-bold text-orange-700">₹{{ number_format($order->grand_total, 2) }}</p></div><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($order->details as $item)<div class="rounded-lg bg-slate-50 px-3 py-2 text-sm"><span class="font-semibold text-slate-700">{{ $item->product_name }}</span><span class="ml-1 text-slate-400">× {{ $item->quantity }}</span><span class="float-right text-orange-700">₹{{ number_format($item->total, 2) }}</span></div>@endforeach</div></div>@empty<div class="p-8 text-center text-sm text-slate-400">No food items ordered for this booking yet.</div>@endforelse</div></section>
    </div></div>
@endsection
