@extends('layout.app')

@section('content')
<div class="row">
    <div class="col-12"><div class="card mb-4"><div class="card-header pb-0 d-flex justify-content-between align-items-center flex-wrap gap-2"><div><h6 class="m-0">Staff Tracking — {{ $pos->name }}</h6><p class="text-xs text-secondary mb-0 mt-1">Salary, advances, leaves and recent tasks</p></div><a href="{{ route('pos_user.view', $pos->id) }}" class="btn btn-outline-secondary btn-sm">Back to Staff List</a></div>
        <div class="card-body"><form method="GET" class="d-flex align-items-end gap-2 mb-4"><div><label class="form-label text-sm mb-1">Salary Month</label><input type="month" name="month" value="{{ $selectedMonth }}" class="form-control"></div><button class="btn btn-primary btn-sm">View</button></form>
            <div class="row mb-4"><div class="col-md-3 mb-3"><div class="border rounded p-3 h-100"><p class="text-xs text-secondary mb-1">Total Staff</p><h5 class="mb-0">{{ $salaryRows->count() }}</h5></div></div><div class="col-md-3 mb-3"><div class="border rounded p-3 h-100"><p class="text-xs text-secondary mb-1">Final Payable</p><h5 class="mb-0 text-success">₹ {{ number_format($salaryRows->sum('finalSalary'), 2) }}</h5></div></div><div class="col-md-3 mb-3"><div class="border rounded p-3 h-100"><p class="text-xs text-secondary mb-1">Salary Advances</p><h5 class="mb-0 text-danger">₹ {{ number_format($advances->sum('amount'), 2) }}</h5></div></div><div class="col-md-3 mb-3"><div class="border rounded p-3 h-100"><p class="text-xs text-secondary mb-1">Recent Tasks</p><h5 class="mb-0">{{ $tasks->count() }}</h5></div></div></div>
            <h6 class="mb-3">Salary Details — {{ $monthStart->format('F Y') }}</h6><div class="table-responsive mb-5"><table class="table align-items-center"><thead><tr><th>Staff</th><th class="text-end">Payable Days</th><th class="text-end">Gross</th><th class="text-end">Leave Deduction</th><th class="text-end">Advances</th><th class="text-end">Final Payable</th></tr></thead><tbody>@forelse($salaryRows as $row)<tr><td><p class="text-xs font-weight-bold mb-0">{{ $row['staff']->name }}</p><p class="text-xs text-secondary mb-0">{{ $row['staff']->staff_id }} · {{ $row['staff']->designation ?: 'Staff' }}</p></td><td class="text-end">{{ $row['payableDays'] }}</td><td class="text-end">₹ {{ number_format($row['grossSalary'], 2) }}</td><td class="text-end text-danger">- ₹ {{ number_format($row['leaveDeduction'], 2) }}</td><td class="text-end text-danger">- ₹ {{ number_format($row['advanceTotal'], 2) }}</td><td class="text-end font-weight-bold text-success">₹ {{ number_format($row['finalSalary'], 2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">No staff found.</td></tr>@endforelse</tbody></table></div>
            <div class="row"><div class="col-lg-6 mb-4"><h6 class="mb-3">Recent Tasks</h6><div class="table-responsive"><table class="table"><thead><tr><th>Staff</th><th>Task</th><th>Date</th></tr></thead><tbody>@forelse($tasks as $task)<tr><td class="text-xs">{{ $task->staff->name ?? '-' }}</td><td><p class="text-xs font-weight-bold mb-0">{{ $task->title }}</p><p class="text-xs text-secondary mb-0">{{ Str::limit($task->description, 55) }}</p></td><td class="text-xs">{{ $task->created_at?->format('d M Y') }}</td></tr>@empty<tr><td colspan="3" class="text-center text-secondary">No tasks found.</td></tr>@endforelse</tbody></table></div></div><div class="col-lg-6 mb-4"><h6 class="mb-3">Leaves in {{ $monthStart->format('F Y') }}</h6><div class="table-responsive"><table class="table"><thead><tr><th>Staff</th><th>Type</th><th>Period</th><th>Status</th></tr></thead><tbody>@forelse($leaves as $leave)<tr><td class="text-xs">{{ $leave->pos->name ?? '-' }}</td><td class="text-xs">{{ $leave->leave_type }}</td><td class="text-xs">{{ \Carbon\Carbon::parse($leave->start_date)->format('d M') }} - {{ \Carbon\Carbon::parse($leave->end_date)->format('d M') }}</td><td><span class="badge badge-sm bg-gradient-{{ $leave->status === 'approved' ? 'success' : ($leave->status === 'rejected' ? 'danger' : 'warning') }}">{{ ucfirst($leave->status) }}</span></td></tr>@empty<tr><td colspan="4" class="text-center text-secondary">No leaves found.</td></tr>@endforelse</tbody></table></div></div></div>
        </div></div></div>
</div>
@endsection
